### ISSUE TITLE
Add support for media queries

### ISSUE THREAD

**Issue by didierfranc** [didierfranc/react-sc#1]
## Issue
Actual engine support regex to add new css features with a simple line
```js
export const toExtract = [
  [ 'PSEUDO_CLASS', /&:[\w-()]+ *{[\n\d\w {}%:;,.()\-#]+}/g ],
  [ 'KEYFRAMES', /@keyframes +\w+ *{[\n\d\w {}%:;,.()\-#]+}/g ],
]
```

We could add support for media queries for this syntax in seconds

```css
@media (max-width: 500px) {
  & { 
    color: red 
  }
  &:hover { 
    color: blue 
  }
}
```
👇
```js
[ 'MEDIA_QUERIES', /(@media +([\d\w-:() ])+(?= .*{)) *{[&\n\d\w {}%:;,.()\-#]+}/g ]
```

## Solution
1. Keep the actual engine use it like above and go skiing
2. Rewrite a part of the engine to remove the `&{}` and support less syntax

_Spoiler I'll make the #2 (after ski)_
